/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.aed.arbitraje;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.api.tree.CaseTree;

/**
 *
 * @author Cesar
 */
public class Plantilla extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Plantilla() {
        initComponents();
        InitStyles();

    }

    private void InitStyles() {
//        title.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
//        title.setForeground(Color.black);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCuentasPorCobrar = new javax.swing.JTable();
        btnBuscarPorDocumento = new javax.swing.JButton();
        txtBuscarDocumento = new javax.swing.JTextField();
        btnRealizarCobro = new javax.swing.JButton();
        jRadioButtonRuc = new javax.swing.JRadioButton();
        jRadioButtonRazonSocial = new javax.swing.JRadioButton();
        jRadioButtonComprobante = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelDeudaTotal = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVerReporte = new javax.swing.JButton();
        btnReporteDeudas = new javax.swing.JButton();
        btnVerReporteCancelados = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jTableCuentasPorCobrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCuentasPorCobrar.setGridColor(new java.awt.Color(255, 255, 255));
        jTableCuentasPorCobrar.setRowSorter(jTableCuentasPorCobrar.getRowSorter());
        jTableCuentasPorCobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCuentasPorCobrarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCuentasPorCobrar);

        btnBuscarPorDocumento.setBackground(new java.awt.Color(18, 90, 173));
        btnBuscarPorDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarPorDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPorDocumento.setText("Buscar");
        btnBuscarPorDocumento.setBorderPainted(false);
        btnBuscarPorDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarPorDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorDocumentoActionPerformed(evt);
            }
        });

        btnRealizarCobro.setBackground(new java.awt.Color(18, 90, 173));
        btnRealizarCobro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRealizarCobro.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarCobro.setText("Cobrar");
        btnRealizarCobro.setBorderPainted(false);
        btnRealizarCobro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRealizarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCobroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRuc);
        jRadioButtonRuc.setText("RUC");

        buttonGroup1.add(jRadioButtonRazonSocial);
        jRadioButtonRazonSocial.setText("RAZON SOCIAL");
        jRadioButtonRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRazonSocialActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonComprobante);
        jRadioButtonComprobante.setSelected(true);
        jRadioButtonComprobante.setText("NRO COMPROBANTE");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Deuda Total:");

        jLabelDeudaTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDeudaTotal.setText("--------");

        header.setBackground(new java.awt.Color(25, 118, 210));
        header.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bandeja De Notificaciones");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVerReporte.setBackground(new java.awt.Color(0, 204, 204));
        btnVerReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporte.setText("Reporte Documento");
        btnVerReporte.setBorderPainted(false);
        btnVerReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActionPerformed(evt);
            }
        });

        btnReporteDeudas.setBackground(new java.awt.Color(255, 51, 51));
        btnReporteDeudas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteDeudas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteDeudas.setText("Reporte Deudas");
        btnReporteDeudas.setBorderPainted(false);
        btnReporteDeudas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDeudasActionPerformed(evt);
            }
        });

        btnVerReporteCancelados.setBackground(new java.awt.Color(0, 204, 51));
        btnVerReporteCancelados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerReporteCancelados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporteCancelados.setText("Reporte Cancelados");
        btnVerReporteCancelados.setBorderPainted(false);
        btnVerReporteCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerReporteCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteCanceladosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jRadioButtonRuc)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonRazonSocial)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonComprobante)
                        .addGap(432, 432, 432))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDeudaTotal)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerReporte)
                                .addGap(18, 18, 18)
                                .addComponent(btnReporteDeudas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtBuscarDocumento)
                                .addGap(14, 14, 14)
                                .addComponent(btnBuscarPorDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnRealizarCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnVerReporteCancelados)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRuc)
                    .addComponent(jRadioButtonRazonSocial)
                    .addComponent(jRadioButtonComprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorDocumento)
                    .addComponent(btnRealizarCobro))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelDeudaTotal)
                    .addComponent(btnVerReporte)
                    .addComponent(btnVerReporteCancelados)
                    .addComponent(btnReporteDeudas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPorDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorDocumentoActionPerformed


    }//GEN-LAST:event_btnBuscarPorDocumentoActionPerformed


    private void btnRealizarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCobroActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnRealizarCobroActionPerformed

    private void jTableCuentasPorCobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCuentasPorCobrarMouseClicked


    }//GEN-LAST:event_jTableCuentasPorCobrarMouseClicked

    private void jRadioButtonRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRazonSocialActionPerformed

    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnVerReporteActionPerformed

    private void btnReporteDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDeudasActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnReporteDeudasActionPerformed

    private void btnVerReporteCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteCanceladosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVerReporteCanceladosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscarPorDocumento;
    private javax.swing.JButton btnRealizarCobro;
    private javax.swing.JButton btnReporteDeudas;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JButton btnVerReporteCancelados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDeudaTotal;
    private javax.swing.JRadioButton jRadioButtonComprobante;
    private javax.swing.JRadioButton jRadioButtonRazonSocial;
    private javax.swing.JRadioButton jRadioButtonRuc;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCuentasPorCobrar;
    private javax.swing.JTextField txtBuscarDocumento;
    // End of variables declaration//GEN-END:variables
}
