package com.dev.aed.arbitraje;


import com.dev.aed.arbitraje.Data.DDemanda;
import com.dev.aed.arbitraje.Data.DRechazarDemanda;
import com.dev.aed.arbitraje.Data.Tabla_PdfVO;
import static com.dev.aed.arbitraje.Demanda.validarNumeroDecimalMayorQueCero;
import com.dev.aed.arbitraje.Model.MDemanda;
import com.dev.aed.arbitraje.Model.MRechazarDemanda;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;



public class RechazarDemanda extends javax.swing.JPanel {
  
//private String numeroExpedienteSeleccionado;
 boolean editar = false;
    MRechazarDemanda demandaEditar;
    
     
     
    public RechazarDemanda() {
        initComponents();
        InitStyles();
        llenarComboArbitro();
        CargarMotivo();
      //  this.numeroExpedienteSeleccionado = numeroExpedienteSeleccionado;
    }
    
  public RechazarDemanda(MRechazarDemanda mDemandaEdit) {
        System.out.println("Inicializando Cuenta CRUD" + mDemandaEdit);
        initComponents();
        editar = true;
        this.demandaEditar = mDemandaEdit;
        InitStyles();
        //  Mostrar(mDemandaEdit);

    }
 
  private void llenarComboArbitro() {
        DRechazarDemanda dRechazarArbitro = new DRechazarDemanda();
        List<String> arbitro = dRechazarArbitro.obtenerArbitro();

        for (String listArbitro : arbitro) {
            cmbArbitro.addItem(listArbitro);
        }
    }
   public void CargarMotivo() {
        DefaultComboBoxModel<String> comboBoxModelMotivo = new DefaultComboBoxModel<>();

        // Agregar elementos al modelo del ComboBox
        comboBoxModelMotivo.addElement("Acuerdo Previo");
        comboBoxModelMotivo.addElement("Desestimado");
        comboBoxModelMotivo.addElement("Otros motivos");

        ddlMotivo.setModel(comboBoxModelMotivo);

    }
  
  
  
    public RechazarDemanda(MDemanda mDemandaEdit) {
        System.out.println("Inicializando Cuenta CRUD" + mDemandaEdit);
        initComponents();
        //editar = true;
        //this.demandaEditar = mDemandaEdit;
        InitStyles();
        //  Mostrar(mDemandaEdit);

    }


    private void InitStyles() {


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGround = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        phoneLbl = new javax.swing.JLabel();
        txtInstancia = new javax.swing.JTextField();
        header1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        phoneLbl3 = new javax.swing.JLabel();
        phoneLbl5 = new javax.swing.JLabel();
        domLbl1 = new javax.swing.JLabel();
        btnGuardarDemanda = new javax.swing.JButton();
        txtNroExpediente = new javax.swing.JTextField();
        ddlMotivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        cmbArbitro = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        bgGround.setBackground(new java.awt.Color(255, 255, 255));

        phoneLbl.setText("Nro Expediente");

        header1.setBackground(new java.awt.Color(25, 118, 210));
        header1.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Demanda");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        phoneLbl3.setText("Instancia de rechazo ");

        phoneLbl5.setText("Motivo");

        domLbl1.setText("Arbitro");

        btnGuardarDemanda.setBackground(new java.awt.Color(18, 90, 173));
        btnGuardarDemanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarDemanda.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarDemanda.setText("Rechazar");
        btnGuardarDemanda.setBorderPainted(false);
        btnGuardarDemanda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarDemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDemandaActionPerformed(evt);
            }
        });

        txtNroExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroExpedienteActionPerformed(evt);
            }
        });

        ddlMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlMotivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha");
        jLabel1.setToolTipText("");

        txtfecha.setText("00/00/2023");

        javax.swing.GroupLayout bgGroundLayout = new javax.swing.GroupLayout(bgGround);
        bgGround.setLayout(bgGroundLayout);
        bgGroundLayout.setHorizontalGroup(
            bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgGroundLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgGroundLayout.createSequentialGroup()
                        .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(bgGroundLayout.createSequentialGroup()
                        .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgGroundLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(phoneLbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(phoneLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGuardarDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgGroundLayout.createSequentialGroup()
                                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgGroundLayout.createSequentialGroup()
                                        .addComponent(ddlMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(domLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(521, 521, 521))))
        );
        bgGroundLayout.setVerticalGroup(
            bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bgGroundLayout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNroExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddlMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnGuardarDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgGround, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ddlMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddlMotivoActionPerformed

    private void btnGuardarDemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDemandaActionPerformed
     
        MRechazarDemanda objDemandaRechazad= new MRechazarDemanda();
        objDemandaRechazad.setNroExpediente(Integer.parseInt(txtNroExpediente.getText()));
        objDemandaRechazad.setMotivo((String) ddlMotivo.getSelectedItem());
        objDemandaRechazad.setFecha((String) txtfecha.getText());
        objDemandaRechazad.setArbitro((String) cmbArbitro.getSelectedItem());
        objDemandaRechazad.setInstancia(txtInstancia.getText());
        //objDemanda.setEstado("Rechazado");
 DRechazarDemanda dRDemanda = new DRechazarDemanda();

      System.out.println("Estado Editar " + editar );
        if (editar == false) {
            System.out.println("Editar Falso");
            int rta = dRDemanda.insertRechazo(objDemandaRechazad);

            if (rta == 1) {
               // Dashboard.ShowJPanel(new Demanda());
                JOptionPane.showMessageDialog(null, "Se Agrego correctamente");
            }
        }
        
   

    }//GEN-LAST:event_btnGuardarDemandaActionPerformed

    private void txtNroExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroExpedienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNroExpedienteActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgGround;
    private javax.swing.JButton btnGuardarDemanda;
    private javax.swing.JComboBox<String> cmbArbitro;
    private javax.swing.JComboBox<String> ddlMotivo;
    private javax.swing.JLabel domLbl1;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneLbl3;
    private javax.swing.JLabel phoneLbl5;
    private javax.swing.JTextField txtInstancia;
    private javax.swing.JTextField txtNroExpediente;
    private javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables
}
