/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.aed.arbitraje;

import static com.dev.aed.arbitraje.Dashboard.ShowJPanel;

public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Reportes() {
        initComponents();
        InitStyles();

    }

    private void InitStyles() {
//        title.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
//        title.setForeground(Color.black);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVerReporte = new javax.swing.JButton();
        btnReporteDeudas = new javax.swing.JButton();
        btnVerReporteCancelados = new javax.swing.JButton();
        btnVerReporteCancelados1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(25, 118, 210));
        header.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reportes");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVerReporte.setBackground(new java.awt.Color(0, 204, 204));
        btnVerReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporte.setText("Generar");
        btnVerReporte.setBorderPainted(false);
        btnVerReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActionPerformed(evt);
            }
        });

        btnReporteDeudas.setBackground(new java.awt.Color(255, 51, 51));
        btnReporteDeudas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteDeudas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteDeudas.setText("Reporte Deudas");
        btnReporteDeudas.setBorderPainted(false);
        btnReporteDeudas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteDeudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDeudasActionPerformed(evt);
            }
        });

        btnVerReporteCancelados.setBackground(new java.awt.Color(0, 204, 51));
        btnVerReporteCancelados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerReporteCancelados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporteCancelados.setText("Reporte Cancelados");
        btnVerReporteCancelados.setBorderPainted(false);
        btnVerReporteCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerReporteCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteCanceladosActionPerformed(evt);
            }
        });

        btnVerReporteCancelados1.setBackground(new java.awt.Color(0, 204, 51));
        btnVerReporteCancelados1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerReporteCancelados1.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReporteCancelados1.setText("Reporte Cancelados");
        btnVerReporteCancelados1.setBorderPainted(false);
        btnVerReporteCancelados1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVerReporteCancelados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteCancelados1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Reporte por Duración de expediente:");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerReporteCancelados1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerReporteCancelados)
                            .addComponent(btnVerReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnReporteDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 395, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnVerReporte))
                .addGap(18, 18, 18)
                .addComponent(btnVerReporteCancelados)
                .addGap(18, 18, 18)
                .addComponent(btnReporteDeudas)
                .addGap(18, 18, 18)
                .addComponent(btnVerReporteCancelados1)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ReporteDuracion());

    }//GEN-LAST:event_btnVerReporteActionPerformed

    private void btnReporteDeudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDeudasActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnReporteDeudasActionPerformed

    private void btnVerReporteCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteCanceladosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVerReporteCanceladosActionPerformed

    private void btnVerReporteCancelados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteCancelados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerReporteCancelados1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnReporteDeudas;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JButton btnVerReporteCancelados;
    private javax.swing.JButton btnVerReporteCancelados1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
